### ISSUE TITLE
Do not commit node_modules and .DS_Store Files

### ISSUE THREAD

**Issue by mtb77** [Ogeran/Modworlds-website#4]
Remove those files and add them to .gitignore

https://git-scm.com/docs/gitignore

**Comment by mtb77** [comment]
Before committing and adding .gitignore you need to delete the files before and commit that. After that you can commit the .gitignore file

**Comment by Ogeran** [comment]
Done

**Comment by mtb77** [comment]
https://github.com/Ogeran/Modworlds-website/blob/main/.DS_Store
https://github.com/Ogeran/Modworlds-website/blob/main/sites/.DS_Store
https://github.com/Ogeran/Modworlds-website/blob/main/recources/.DS_Store
https://github.com/Ogeran/Modworlds-website/blob/main/recources/graphics/.DS_Store
https://github.com/Ogeran/Modworlds-website/blob/main/recources/graphics/pictures/.DS_Store

**Comment by Ogeran** [comment]
Deleted them :)
